// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAKeEBGPMnP42Uxmo0u1OwXaWbl05zylA',
    appId: '1:721702625231:web:9065a1d58108d7c1a6bcba',
    messagingSenderId: '721702625231',
    projectId: 'fir-mart-2670a',
    authDomain: 'fir-mart-2670a.firebaseapp.com',
    storageBucket: 'fir-mart-2670a.appspot.com',
    measurementId: 'G-DJCS28L7XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUVMrtlp4OxkFMHIDe_crX7MQY_SYh5c',
    appId: '1:721702625231:android:f770542ea361e840a6bcba',
    messagingSenderId: '721702625231',
    projectId: 'fir-mart-2670a',
    storageBucket: 'fir-mart-2670a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhpsg4Gv2qczv45HWCkAj08ASTggHVdE',
    appId: '1:721702625231:ios:4b290bb3f9f103cea6bcba',
    messagingSenderId: '721702625231',
    projectId: 'fir-mart-2670a',
    storageBucket: 'fir-mart-2670a.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEhpsg4Gv2qczv45HWCkAj08ASTggHVdE',
    appId: '1:721702625231:ios:4b290bb3f9f103cea6bcba',
    messagingSenderId: '721702625231',
    projectId: 'fir-mart-2670a',
    storageBucket: 'fir-mart-2670a.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAKeEBGPMnP42Uxmo0u1OwXaWbl05zylA',
    appId: '1:721702625231:web:be8ec8533e1f57dca6bcba',
    messagingSenderId: '721702625231',
    projectId: 'fir-mart-2670a',
    authDomain: 'fir-mart-2670a.firebaseapp.com',
    storageBucket: 'fir-mart-2670a.appspot.com',
    measurementId: 'G-58KTWVVV2Y',
  );
}
